export default {
  MatchAnalyticsWelcome: "BEM-VINDO À ANÁLISE DE PARTIDA",
  MatchAnalyticsIntro:
    "Jogue uma partida com o Dota Coach para poder usar a Análise de Partida e comparar seu desempenho com outros jogadores.",
  SupportedLobbies: "Lobbies apoiados",
  SupportedLobbiesList: "Competitiva e casual.",
  SupportedRankedModes: "Modos competitivos compatíveis",
  SupportedRankedModesList: "Escolha livre, modo de capitães e seleção aleatória.",
  SupportedUnrankedModes: "Modos casuais compatíveis",
  SupportedUnrankedModesList:
    "Escolha livre, turbo, seleção individual, seleção aleatória e todos aleatórios.",

  You: "Você",
  Peers: "Outros",
  Benchmark: "Referência",

  Leaderboard: "Entre os melhores",
  LoadingLeaderboard: "Carregando",
  LoadingLeaderboardFailed:
    "Falha no carregamento da tabela de classificação. Por favor, tente novamente.",
  Loaded: "Carregado",
  TryAgain: "Tente novamente",

  Match: "Partida",
  Result: "Resultado",
  Won: "Ganhou",
  Lost: "Perdeu",
  Length: "Duração",
  Mode: "Modo",
  ID: "ID da partida",
  OpenDota: "OpenDota",
  ViewMatch: "Ver partida",
  Hero: "Herói",
  SteamGuide: "Steam guide",
  Heropedia: "Heroipedia",
  ViewHero: "Ver herói",
  OneMatch: "1 partida",
  NumberMatches: "{match_count} partidas",
  OurCoaches: "Nossos treinadores",
  na: "n/a",

  LaningPhase: "Fase de trilha",
  MidAndLateGame: "Mid e late game",
  LargeItems: "Itens grandes",
  lastHits: "Últimos acessos",
  denies: "Negados",
  kills: "Vítimas",
  deaths: "Mortes",
  assists: "Assistências",
  InMatch: "Em partida",
  gpm: "GPM",
  Percentile75: "percentil 75",
  Percentile25: "percentil 25",
};
