export default {
  MatchAnalyticsWelcome: "WILLKOMMEN BEI DER SPIELANALYSE",
  MatchAnalyticsIntro:
    "Spiele ein Match mit Dota Coach, um die Spielanalyse nutzen zu können und deine Leistung mit anderen Spielern zu vergleichen.",
  SupportedLobbies: "Unterstützte Lobbys",
  SupportedLobbiesList: "Ranked und unranked.",
  SupportedRankedModes: "Unterstützte ranked Modi",
  SupportedRankedModesList: "Alle wählen, Kapitänsmodus und zufälliger Entwurf.",
  SupportedUnrankedModes: "Unterstützte unranked Modi",
  SupportedUnrankedModesList:
    "Alle Auswahl, Turbo, Einzelentwurf, zufälliger Entwurf, alles zufällig.",

  You: "Du",
  Peers: "Peers",
  Benchmark: "Benchmark",

  Leaderboard: "Bestenliste",
  LoadingLeaderboard: "Wird geladen",
  LoadingLeaderboardFailed:
    "Das Laden der Bestenliste ist fehlgeschlagen. Bitte versuche es erneut.",
  Loaded: "Geladen",
  TryAgain: "Versuche es nochmal",

  Match: "Spiel",
  Result: "Ergebnis",
  Won: "Gewonnen",
  Lost: "Verloren",
  Length: "Dauer",
  Mode: "Modus",
  ID: "ID",
  OpenDota: "OpenDota",
  ViewMatch: "Siel ansehen",
  Hero: "Held",
  SteamGuide: "Steam guide",
  Heropedia: "Heropedia",
  ViewHero: "Held ansehen",
  OneMatch: "1 Spiel",
  NumberMatches: "{match_count} Spiele",
  OurCoaches: "Unsere Coaches",
  na: "n/a",

  LaningPhase: "Laning-Phase",
  MidAndLateGame: "Mittleres und spätes Spiel",
  LargeItems: "Große Gegenstände",
  lastHits: "Last hits",
  Denies: "Denies",
  Kills: "Kills",
  Deaths: "Tode",
  assists: "Assists",
  InMatch: "Im Spiel",
  gpm: "GPM",
  Percentile75: "75. Perzentil",
  Percentile25: "25. Perzentil",
};
