export default {
  MatchAnalyticsWelcome: "BIENVENIDO A ANÁLISIS DE PARTIDOS",
  MatchAnalyticsIntro:
    "Juega un partido con Dota Coach para poder usar Match Analytics y comparar tu rendimiento con el de otros jugadores.",
  SupportedLobbies: "Lobbies compatibles",
  SupportedLobbiesList: "Clasificados y no clasificados.",
  SupportedRankedModes: "Modos clasificados compatibles",
  SupportedRankedModesList: "Todas las selecciones, modo capitanes y draft aleatorio.",
  SupportedUnrankedModes: "Modos no clasificados compatibles",
  SupportedUnrankedModesList:
    "Todas las selecciones, turbo, borrador simple, borrador aleatorio, todo aleatorio.",

  You: "Tú",
  Peers: "Pares",
  Benchmark: "Referencia",

  Leaderboard: "Tabla de clasificación",
  LoadingLeaderboard: "Cargando",
  LoadingLeaderboardFailed: "La carga de la tabla de clasificación falló. Inténtalo de nuevo.",
  Loaded: "Cargado",
  TryAgain: "Intentar otra vez",

  Match: "Partido",
  Result: "Resultado",
  Won: "Ganó",
  Lost: "Perdido",
  Length: "Longitud",
  Mode: "Moda",
  ID: "ID",
  OpenDota: "OpenDota",
  ViewMatch: "Ver partido",
  Hero: "Héroe",
  SteamGuide: "Steam guide",
  Heropedia: "Heropedia",
  ViewHero: "Ver héroe",
  OneMatch: "1 partido",
  NumberMatches: "{match_count} partidos",
  OurCoaches: "Nuestros entrenadores",
  na: "n/a",

  LaningPhase: "Fase de aterrizaje",
  MidAndLateGame: "Juego medio y tardío",
  LargeItems: "Artículos grandes",
  lastHits: "Últimos éxitos",
  denies: "Niega",
  kills: "Muertes",
  deaths: "Defunciones",
  assists: "Asistencias",
  InMatch: "En match",
  gpm: "GPM",
  Percentile75: "percentil 75",
  Percentile25: "percentil 25",
};
