export default {
  MatchAnalyticsWelcome: "MALIGAYANG PAGDATING UPANG TUMUGMA SA ANALYTICS",
  MatchAnalyticsIntro:
    "Maglaro ng isang tugma sa Dota Coach upang magamit ang Match Analytics at upang ihambing ang iyong pagganap sa iba pang mga manlalaro.",
  SupportedLobbies: "Mga sinusuportahang lobbies",
  SupportedLobbiesList: "Niraranggo at walang ranggo.",
  SupportedRankedModes: "Sinusuportahang mga mode ng ranggo",
  SupportedRankedModesList: "Lahat ng pick, captains mode at random draft.",
  SupportedUnrankedModes: "Mga suportadong hindi naka-ranggo na mga mode",
  SupportedUnrankedModesList: "Lahat ng pick, turbo, solong draft, random draft, lahat ng random.",

  You: "Ikaw",
  Peers: "Mga kapantay",
  Benchmark: "Benchmark",

  Leaderboard: "Leaderboard",
  LoadingLeaderboard: "Naglo-load",
  LoadingLeaderboardFailed: "Nabigo ang pag-load ng leaderboard. Pakisubukang muli.",
  Loaded: "Puno",
  TryAgain: "Subukan muli",

  Match: "Pareha",
  Result: "Resulta",
  Won: "Won",
  Lost: "Nawala",
  Length: "Haba",
  Mode: "Mode",
  ID: "ID",
  OpenDota: "OpenDota",
  ViewMatch: "Tingnan ang laban",
  Hero: "Bayani",
  SteamGuide: "Steam guide",
  Heropedia: "Heropedia",
  ViewHero: "Tingnan ang bayani",
  OneMatch: "1 tugma",
  NumberMatches: "{match_count} tugma",
  OurCoaches: "Ang aming mga coach",
  na: "n/a",

  LaningPhase: "Laning phase",
  MidAndLateGame: "Mid at huli na laro",
  LargeItems: "Malaking mga item",

  lastHits: "Huling hit",
  denies: "Tinanggihan",
  kills: "Pumapatay",
  deaths: "Pagkamatay",
  assists: "Tumutulong",
  InMatch: "Sa tugma",
  gpm: "GPM",
  Percentile75: "75 porsiyento",
  Percentile25: "25 porsiyento",
};
