export default {
  MatchAnalyticsWelcome: "BIENVENUE DANS L'ANALYSE DES MATCHS",
  MatchAnalyticsIntro:
    "Jouez un match avec Dota Coach pour pouvoir utiliser l'analyse des matchs et comparer vos performances avec celles des autres joueurs.",
  SupportedLobbies: "Lobbies soutenue",
  SupportedLobbiesList: "Classé et non classé.",
  SupportedRankedModes: "Modes ranked soutenus",
  SupportedRankedModesList: "Tous les choix, le mode capitaines et le draft aléatoire.",
  SupportedUnrankedModes: "Modes unranked pris en charge",
  SupportedUnrankedModesList: "Tout pick, turbo, simple draft, draft aléatoire, tout aléatoire.",

  You: "Toi",
  Peers: "Pairs",
  Benchmark: "Repère",

  Leaderboard: "Classement",
  LoadingLeaderboard: "Chargement",
  LoadingLeaderboardFailed: "Le chargement du classement a échoué. Veuillez réessayer.",
  Loaded: "Chargée",
  TryAgain: "Réessayer",

  Match: "Jeu",
  Result: "Résultat",
  Won: "Gagné",
  Lost: "Perdu",
  Length: "Durée",
  Mode: "Mode",
  ID: "ID",
  OpenDota: "OpenDota",
  ViewMatch: "Voir le jeu",
  Hero: "Héro",
  SteamGuide: "Steam guide",
  Heropedia: "Héropedia",
  ViewHero: "Voir l'héro",
  OneMatch: "1 jeu",
  NumberMatches: "{match_count} jeux",
  OurCoaches: "Nos coachs",
  na: "n/a",

  LaningPhase: "Phase d'atterrissage",
  MidAndLateGame: "Mid & late game",
  LargeItems: "Articles de grande taille",
  lastHits: "Derniers coups",
  denies: "Refuse",
  kills: "Tue",
  deaths: "Morts",
  assists: "Aides",
  InMatch: "En match",
  gpm: "GPM",
  Percentile75: "75 centile",
  Percentile25: "25 centile",
};
