export default {
  MatchAnalyticsWelcome: "SELAMAT DATANG UNTUK MENCOCOKKAN ANALISIS",
  MatchAnalyticsIntro:
    "Mainkan pertandingan dengan Dota Coach untuk dapat menggunakan Match Analytics dan membandingkan kinerja Anda dengan pemain lain.",
  SupportedLobbies: "Lobi yang didukung",
  SupportedLobbiesList: "Peringkat dan unranking.",
  SupportedRankedModes: "Mode peringkat yang didukung",
  SupportedRankedModesList: "Semua memilih, mode kapten dan draft acak.",
  SupportedUnrankedModes: "Mode unranked yang didukung",
  SupportedUnrankedModesList: "Semua pick, turbo, draft tunggal, draft acak, semua acak.",

  You: "Anda",
  Peers: "Rekan-rekan",
  Benchmark: "Tolok ukur",

  Leaderboard: "Papan peringkat",
  LoadingLeaderboard: "Memuat",
  LoadingLeaderboardFailed: "Pemuatan papan peringkat gagal. Silakan coba lagi.",
  Loaded: "Sarat",
  TryAgain: "Coba lagi",

  Match: "Pertandingan",
  Result: "Hasil",
  Won: "Menang",
  Lost: "Hilang",
  Length: "Panjangnya",
  Mode: "Modus",
  ID: "ID",
  OpenDota: "OpenDota",
  ViewMatch: "Lihat pertandingan",
  Hero: "Pahlawan",
  SteamGuide: "Steam guide",
  Heropedia: "Heropedia",
  ViewHero: "Lihat pahlawan",
  OneMatch: "1 pertandingan",
  NumberMatches: "{match_count} pertandingan",
  OurCoaches: "Pelatih kami",
  na: "n/a",

  LaningPhase: "fase laning",
  MidAndLateGame: "Pertengahan & akhir permainan",
  LargeItems: "Item besar",
  lastHits: "Last hits",
  denies: "Menyangkal",
  kills: "Membunuh",
  deaths: "Kematian",
  assists: "Bantuan",
  nMatch: "Dalam pertandingan",
  gpm: "GPM",
  Percentile75: "75 persentil",
  Percentile25: "25 persentil",
};
