export default {
  MatchAnalyticsWelcome: "ДОБРО ПОЖАЛОВАТЬ В АНАЛИТИКУ МАТЧА",
  MatchAnalyticsIntro:
    "Сыграйте матч с Dota Coach, чтобы использовать аналитику матчей и сравнить свои результаты с результатами других игроков.",
  SupportedLobbies: "Поддерживаемые лобби",
  SupportedLobbiesList: "Рейтинговые и безрейтинговые.",
  SupportedRankedModes: "Поддерживаемые рейтинговые режимы",
  SupportedRankedModesList: "Режим всех пиков, капитанов и случайный драфт.",
  SupportedUnrankedModes: "Поддерживаемые безрейтинговые режимы",
  SupportedUnrankedModesList: "Весь выбор, турбо, одиночный выбор, случайный выбор, все случайные.",

  You: "Вы",
  Peers: "Игроки на ранге",
  Benchmark: "Контрольный показатель",

  Leaderboard: "Таблица лидеров",
  LoadingLeaderboard: "Загрузка",
  LoadingLeaderboardFailed: "Не удалось загрузить таблицу лидеров. Пожалуйста, попробуйте еще раз.",
  Loaded: "Загружено",
  TryAgain: "Попробуйте еще раз",

  Match: "Матч",
  Result: "Результат",
  Won: "Победа",
  Lost: "Поражение",
  Length: "Длительность",
  Mode: "Режим",
  ID: "ID",
  OpenDota: "OpenDota",
  ViewMatch: "Посмотреть матч",
  Hero: "Герой",
  SteamGuide: "Steam guide",
  Heropedia: "Геропедия",
  ViewHero: "Посмотреть героя",
  OneMatch: "1 матч",
  NumberMatches: "{match_count} матчей",
  OurCoaches: "Наши тренеры",
  na: "n/a",

  LaningPhase: "Фаза лайнинга",
  MidAndLateGame: "Средняя и поздняя игра",
  LargeItems: "Ключевые предметы",
  lastHits: "Последние хиты",
  denies: "Денаи",
  kills: "Убийства",
  deaths: "Смерти",
  assists: "Ассистирует",
  InMatch: "В матче",
  gpm: "GPM",
  Percentile75: "75 процентиль",
  Percentile25: "25 процентиль",
};
