export default {
  MatchAnalyticsWelcome: "欢迎使用匹配分析",
  MatchAnalyticsIntro: "与Dota Coach进行一场比赛，即可使用比赛分析并比较你与其他牌手的表现。",
  SupportedLobbies: "支持的大厅",
  SupportedLobbiesList: "排名和未排名。",
  SupportedRankedModes: "支持的排名模式",
  SupportedRankedModesList: "全选、队长模式和随机选秀。",
  SupportedUnrankedModes: "支持的未排序模式",
  SupportedUnrankedModesList: "所有选择、turbo、单草稿、随机草稿，都是随机的。",

  You: "你",
  Peers: "同行",
  Benchmark: "基准",

  Leaderboard: "排行榜",
  LoadingLeaderboard: "正在加载",
  LoadingLeaderboardFailed: "排行榜加载失败。请再试一次。",
  Loaded: "已加载",
  TryAgain: "再试一次",

  Match: "匹配",
  Result: "结果",
  Won: "赢了",
  Lost: "迷路了",
  Length: "长度",
  Mode: "模式",
  ID: "身份证",
  OpenDota: "OpenDota",
  ViewMatch: "查看比赛",
  Hero: "英雄",
  SteamGuide: "Steam guide",
  Heropedia: "Heropedia",
  ViewHero: "查看英雄",
  OneMatch: "1 场比赛",
  NumberMatches: "{match_count} 场比赛",
  OurCoaches: "我们的教练",
  na: "不适用",

  LaningPhase: "着陆阶段",
  MidAndLateGame: "游戏中后期",
  LargeItems: "大件物品",
  lastHits: "最后命中",
  denies: "否认",
  kills: "击杀",
  deaths: "死亡",
  assists: "助攻",
  InMatch: "在比赛中",
  gpm: "GPM",
  Percentile75: "75百分位数",
  Percentile25: "25百分位数",
};
