export default {
	Services: "Serviços",
	InternetConnectivity: "Conectividade à Internet",
	Online: "On-line",
	Offline: "Off-line",
	Dota2: "Dota 2",
	Running: "Corrida",
	NotRunning: "Não está correndo",
	OverwolfPlugin: "Plugin Overwolf",
	Operational: "Operacional",
	PluginFailedInitializing: "Falha ao inicializar",
	PluginCrashed: "Caiu",
	PluginUnknownError: "Erro desconhecido",
	FurtherInformation: "Para obter mais informações, acesse Notificações",
	Dota2Connection: "Conexão Dota 2",
	NotInitiated: "Não iniciado",
	OverwolfServices: "Serviços Overwolf",
	Down: "Para baixo",
	DotaCoachServices: "Serviços do Dota Coach",
	Idle: "Ocioso",
	Connected: "Conectado",
	NotRegistered: "Não registrado",
	YourConfiguration: "Sua configuração",
	GSI: "Integração do estado do jogo (Steam)",
	DotaOverlay: "Sobreposição de Dota 2 (Overwolf)",
	Enabled: "Habilitado",
	Missing: "Desaparecido",
	Activated: "Ativado",
	Typo: "Erro de digitação",
	Unknown: "Desconhecido",
	RestartNeeded: "É necessário reiniciar",
	Partial: "Parcial",
	Connecting: "Conectando...",
	Loading: "Carregando...",
	LoadingFailed: "Falha no carregamento",
}
