export default {
	Services: "Dienstleistungen",
	InternetConnectivity: "Internetkonnektivität",
	Online: "Online",
	Offline: "Offline",
	Dota2: "Dota 2",
	Running: "Running",
	NotRunning: "Läuft nicht",
	OverwolfPlugin: "Overwolf-Plugin",
	Operational: "Operative",
	PluginFailedInitializing: "Initialisierung fehlgeschlagen",
	PluginCrashed: "Abgestürzt",
	PluginUnknownError: "Unbekannter Fehler",
	FurtherInformation: "Weitere Informationen finden Sie unter Benachrichtigungen",
	NotInitiated: "Nicht initiiert",
	Dota2Connection: "Dota 2-Verbindung",
	OverwolfServices: "Overwolf-Dienste",
	Down: "Down",
	DotaCoachServices: "Dota Coach-Dienste",
	Idle: "Inaktiv",
	Connected: "Verbunden",
	NotRegistered: "Nicht registriert",
	YourConfiguration: "Deine Konfiguration",
	GSI: "Integration des Spielzustands (Steam)",
	DotaOverlay: "Dota 2 Overlay (Overwolf)",
	Enabled: "Aktiviert",
	Missing: "Fehlt",
	Activated: "Aktiviert",
	Typo: "Tippfehler",
	Unknown: "Unbekannt",
	RestartNeeded: "Neustart erforderlich",
	Partial: "Teilweise",
	Connecting: "Verbindung wird hergestellt...",
	Loading: "Wird geladen...",
	LoadingFailed: "Laden ist fehlgeschlagen",
}
