export default {
	Services: "Servicios",
	InternetConnectivity: "conectividad a Internet",
	Online: "En línea",
	Offline: "Offline",
	Dota2: "Dota 2",
	Running: "Correr",
	NotRunning: "No se está ejecutando",
	OverwolfPlugin: "Complemento Overwolf",
	Operational: "Operacional",
	PluginFailedInitializing: "Fallo al inicializar",
	PluginCrashed: "Se estrelló",
	PluginUnknownError: "Error desconocido",
	FurtherInformation: "Para obtener más información, vaya a notificaciones",
	Dota2Connection: "Conexión Dota 2",
	NotInitiated: "No iniciado",
	OverwolfServices: "Servicios Overwolf",
	Down: "Abajo",
	DotaCoachServices: "Servicios de Dota Coach",
	Idle: "Ocioso",
	Connected: "Conexo",
	NotRegistered: "No registrado",
	YourConfiguration: "Su configuración",
	GSI: "Integración del estado del juego (Steam)",
	DotaOverlay: "Superposición de Dota 2 (Overwolf)",
	Enabled: "Activado",
	Missing: "Desaparecido",
	Activated: "Activado",
	Unknown: "Desconocido",
	Typo: "Error tipográfico",
	Partial: "Parcial",
	RestartNeeded: "Es necesario reiniciar",
	Connecting: "Conectando...",
	Loading: "Cargando...",
	LoadingFailed: "Fallo al cargar",
}
