export default {
	Services: "Mga Serbisyo",
	InternetConnectivity: "Koneksyon sa internet",
	Online: "Online",
	Offline: "Offline",
	Dota2: "Dota 2",
	Running: "Tumatakbo",
	NotRunning: "Hindi tumatakbo",
	OverwolfPlugin: "Overwolf plugin",
	Operational: "Pagpapatakbo",
	PluginFailedInitializing: "Nabigo ang pagsisimula",
	PluginCrashed: "Nag-crash",
	PluginUnknownError: "Hindi kilalang error",
	FurtherInformation: "Para sa karagdagang impormasyon pumunta sa mga notification",
	Dota2Connection: "Koneksyon ng Dota 2",
	NotInitiated: "Hindi pinasimulan",
	OverwolfServices: "Mga serbisyo ng Overwolf",
	Down: "Down",
	DotaCoachServices: "Dota Coach serbisyo",
	Idle: "Idle",
	Connected: "Konektadong",
	NotRegistered: "Hindi nakarehistro",
	YourConfiguration: "Ang iyong configuration",
	GSI: "Pagsasama ng estado ng laro (Steam)",
	DotaOverlay: "Overlay ng Dota 2 (Overwolf)",
	Enabled: "Pinagana",
	Missing: "Nawawala",
	Activated: "Isinaaktibo",
	Typo: "Typo",
	Unknown: "Hindi kilalang",
	RestartNeeded: "Kinakailangan ang restart",
	Partial: "Bahagyang",
	Connecting: "Kumokonekta...",
	Loading: "Naglo-load...",
	LoadingFailed: "Nabigo ang pag-load",
}
