export default {
	Services: "Les services",
	InternetConnectivity: "Connectivité Internet",
	Online: "En ligne",
	Offline: "hors ligne",
	Dota2: "Dota 2",
	Running: "Courir",
	NotRunning: "Ne fonctionne pas",
	OverwolfPlugin: "Plug-in Overwolf",
	Operational: "Exploitation",
	PluginFailedInitializing: "Échec de l'initialisation",
	PluginUnknownError: "Erreur inconnue",
	Dota2Connection: "Connexion Dota 2",
	FurtherInformation: "Pour plus d'informations, consultez la rubrique Notifications",
	PluginCrashed: "Crashed",
	OverwolfServices: "Services Overwolf",
	Down: "En bas",
	NotInitiated: "Non initié",
	DotaCoachServices: "Services Dota Coach",
	Idle: "Inactif",
	Connected: "Connecté",
	NotRegistered: "Non enregistré",
	GSI: "Intégration de l'état du jeu (Steam)",
	YourConfiguration: "Votre configuration",
	DotaOverlay: "Superposition Dota 2 (Overwolf)",
	Enabled: "Activé",
	Missing: "Manquant",
	Activated: "Activé",
	Typo: "faute de frappe",
	Unknown: "Inconnu",
	RestartNeeded: "Redémarrage nécessaire",
	Partial: "Partiel",
	Connecting: "Connexion en cours...",
	Loading: "Chargement...",
	LoadingFailed: "Échec du chargement",
}
