export default {
	Services: "Jasa",
	InternetConnectivity: "Konektivitas internet",
	Online: "Daring",
	Offline: "Offline",
	Running: "Menjalankan",
	NotRunning: "Tidak berjalan",
	OverwolfPlugin: "Plugin serigala",
	Dota2: "Dota 2",
	Operational: "Operasional",
	PluginFailedInitializing: "Gagal menginisialisasi",
	PluginCrashed: "Jatuh",
	PluginUnknownError: "Kesalahan tak dikenal",
	FurtherInformation: "Untuk informasi lebih lanjut, buka notifikasi",
	Dota2Connection: "Koneksi Dota 2",
	NotInitiated: "Tidak dimulai",
	OverwolfServices: "Layanan Overwolf",
	Down: "Turun",
	DotaCoachServices: "Layanan Dota Coach",
	Idle: "Menganggur",
	Connected: "Terhubung",
	NotRegistered: "Tidak terdaftar",
	YourConfiguration: "Konfigurasi Anda",
	GSI: "Integrasi negara game (Steam)",
	DotaOverlay: "Hamparan Dota 2 (Overwolf)",
	Enabled: "Diaktifkan",
	Missing: "Hilang",
	Activated: "Diaktifkan",
	Typo: "Kesalahan ketik",
	Unknown: "Tidak diketahui",
	RestartNeeded: "Restart diperlukan",
	Partial: "parsial",
	Connecting: "Menghubungkan...",
	Loading: "Memuat...",
	LoadingFailed: "Memuat gagal",
}
