export default {
	Services: "Сервисы",
	InternetConnectivity: "Подключение к Интернету",
	Online: "Онлайн",
	Offline: "Офлайн",
	Dota2: "Дота 2",
	Running: "Бег",
	NotRunning: "Не запущен",
	OverwolfPlugin: "Плагин Овервольф",
	Operational: "Оперативный",
	PluginFailedInitializing: "Не удалось инициализировать",
	PluginCrashed: "Разбился",
	PluginUnknownError: "Неизвестная ошибка",
	FurtherInformation: "Для получения дополнительной информации перейдите в раздел «Уведомления»",
	Dota2Connection: "Подключение к Dota 2",
	NotInitiated: "Не инициировано",
	OverwolfServices: "Услуги Overwolf",
	Down: "Вниз",
	DotaCoachServices: "Услуги тренера по Dota",
	Idle: "Холостой ход",
	Connected: "Подключено",
	YourConfiguration: "Ваша конфигурация",
	NotRegistered: "Не зарегистрирован",
	GSI: "Интеграция игрового состояния (Steam)",
	DotaOverlay: "Оверлей Dota 2 (Овервольф)",
	Enabled: "Включено",
	Missing: "Отсутствует",
	Activated: "Активированный",
	Typo: "Опечатка",
	Unknown: "Неизвестно",
	RestartNeeded: "Требуется перезапуск",
	Partial: "Частичная",
	Connecting: "Подключение...",
	Loading: "Загрузка...",
	LoadingFailed: "Загрузка не удалась",
}
