export default {
	Services: "服务",
	InternetConnectivity: "互联网连接",
	Online: "线上",
	Offline: "离线",
	Dota2: "刀塔 2",
	Running: "跑步",
	NotRunning: "没有运行",
	OverwolfPlugin: "狼人插件",
	Operational: "运营",
	PluginFailedInitializing: "初始化失败",
	PluginCrashed: "坠毁",
	PluginUnknownError: "未知错误",
	FurtherInformation: "有关更多信息，请转到通知",
	Dota2Connection: "刀塔 2 连接",
	NotInitiated: "未启动",
	OverwolfServices: "Overwolf 服务",
	Down: "向下",
	DotaCoachServices: "刀塔教练服务",
	Idle: "空闲",
	Connected: "已连接",
	NotRegistered: "未注册",
	YourConfiguration: "你的配置",
	GSI: "游戏状态集成 (Steam)",
	DotaOverlay: "刀塔 2 叠加（狼人）",
	Enabled: "已启用",
	Missing: "失踪",
	Activated: "已激活",
	Typo: "错字",
	Unknown: "未知",
	RestartNeeded: "需要重启",
	Partial: "局部的",
	Connecting: "正在连接...",
	Loading: "加载中...",
	LoadingFailed: "加载失败",
}
