export default {
  FEEDBACK: {
    en: "FEEDBACK",
    de: "FEEDBACK",
    fr: "COMMENTAIRES",
    ru: "ОТЗЫВ",
    id: "UMPAN BALIK",
    fil: "FEEDBACK",
    zh: "反馈",
    br: "COMENTÁRIOS",
    es: "COMENTARIOS",
  },
  ReportAnIssue: {
    en: "Report an issue/bug or request support",
    de: "Ein Problem/Bug melden oder Support anfragen",
    fr: "Signaler un problème/un bogue ou demander de l'aide",
    ru: "Сообщить об ошибке или обратиться в поддержку",
    id: "Melaporkan masalah/bug atau meminta dukungan",
    fil: "Mag-report ng issue/bug o mag-request ng support",
    zh: "报告问题/错误或请求支持",
    br: "Reportar um problema",
    es: "Reportar un problema",
  },
  ShareWithUs: {
    en: "What do you want to share with us?",
    de: "Was möchtest du mit uns teilen?",
    fr: "Qu'est-ce que tu souhaites partager avec nous ?",
    ru: "Чем вы хотите с нами поделиться?",
    id: "Apa yang ingin Anda bagikan dengan kami?",
    fil: "Ano gusto mong i-share sa amin?",
    zh: "给开发团队留言",
    br: "O que você gostaria de compartilhar conosco?",
    es: "¿Qué quieres compartir con nosotros?",
  },
  IssueDescription: {
    en: "Enter description of issue/bug or request for support",
    de: "Geben Sie eine Beschreibung des Problems/Bugs oder eine Supportanfrage ein",
    fr: "Entrez la description du problème/du bogue ou de la demande d'assistance",
    ru: "Введите описание ошибки или запросите поддержку",
    id: "Masukkan deskripsi masalah/bug atau permintaan untuk dukungan",
    fil: "Ilagay ang description ng issue/bug or request ng support",
    zh: "输入问题/错误描述或请求支持",
    br: "Descreva o problema/bug ou pedido de suporte",
    es: "Descripción del problema",
  },
  SEND_REPORT: {
    en: "SEND REPORT",
    de: "BERICHT SENDEN",
    fr: "ENVOYER UN RAPPORT",
    ru: "ОТПРАВИТЬ ОТЧЕТ",
    id: "KIRIM LAPORAN",
    fil: "SEND REPORT",
    zh: "发送报告",
    br: "ENVIAR REPORTE",
    es: "ENVIAR REPORTE",
  },
  ContactDetails: {
    en: "Contact details (E-Mail/Discord)",
    de: "Kontaktdaten (E-Mail/Discord)",
    fr: "Coordonnées (E-Mail/Discord)",
    ru: "Контактные данные (E-Mail/Discord)",
    id: "Rincian kontak (E-Mail/Perselisihan)",
    fil: "Contact details (E-Mail/Discord)",
    zh: "联系方式（电子邮件/Discord）",
    br: "Detalhes de contato (E-Mail/Discord)",
    es: "Detalles de contacto (E-Mail/Discord)",
  },
  EnterContactDetails: {
    en: "Enter your contact details",
    de: "Gib deine Kontaktdaten ein",
    fr: "Entrez vos coordonnées",
    ru: "Введите свои контактные данные",
    id: "Masukkan detail kontak Anda",
    fil: "Ilagay mo ang iyong contact details",
    zh: "输入您的联系方式",
    br: "Insira seus detalhes de contato",
    es: "Ingrese sus datos de contacto",
  },
  LogFiles: {
    en: "Attach Dota Coach log files",
    de: "Dota Coach-Protokolldateien anhängen",
    fr: "Joindre les fichiers journaux Dota Coach",
    ru: "Прикрепить файлы журнала Dota Coach",
    id: "Lampirkan file log Dota Coach",
    fil: "Attach Dota Coach log files",
    zh: "附上 Dota Coach 日志文件",
    br: "Anexar arquivos de registro do Dota Coach",
    es: "Adjunta los archivos de registro de Dota Coach",
  },
};
