export default {
  ShareWithUs: {
    en: "What do you want to share with us?",
    de: "Was möchtest du mit uns teilen?",
    fr: "Qu'est-ce que tu souhaites partager avec nous ?",
    ru: "Чем вы хотите с нами поделиться?",
    id: "Apa yang ingin Anda bagikan dengan kami?",
    fil: "Ano gusto mong i-share sa amin?",
    zh: "给开发团队留言",
    br: "O que você gostaria de compartilhar conosco?",
    es: "¿Qué quieres compartir con nosotros?",
  },
  IssueDescription: {
    en: "Enter description of issue/bug or request for support",
    de: "Geben Sie eine Beschreibung des Problems/Bugs oder eine Supportanfrage ein",
    fr: "Entrez la description du problème/du bogue ou de la demande d'assistance",
    ru: "Введите описание ошибки или запросите поддержку",
    id: "Masukkan deskripsi masalah/bug atau permintaan untuk dukungan",
    fil: "Ilagay ang description ng issue/bug or request ng support",
    zh: "输入问题/错误描述或请求支持",
    br: "Descreva o problema/bug ou pedido de suporte",
    es: "Descripción del problema",
  },

  LogFiles: {
    en: "Attach Dota Coach log files",
    de: "Dota Coach-Protokolldateien anhängen",
    fr: "Joindre les fichiers journaux Dota Coach",
    ru: "Прикрепить файлы журнала Dota Coach",
    id: "Lampirkan file log Dota Coach",
    fil: "Attach Dota Coach log files",
    zh: "附上 Dota Coach 日志文件",
    br: "Anexar arquivos de registro do Dota Coach",
    es: "Adjunta los archivos de registro de Dota Coach",
  },
};
