export default {
  Heroes: "Helden",
  Team: "Team",
  Timers: "Timer",
  Runes: "Runen",
  Audio: "Audio",
  Disabled: "Deaktiviert",
  Speaker: "Lautsprecher",
  Volume: "Volumen",
  Test: "Testen",
  Language: "Sprache",
  Infoboxes: "Infoboxen",

  None: "Keiner",
  Alt: "Alt",
  Ctrl: "Strg",
  Shift: "Umschalttaste",

  Settings: "Einstellungen",
  MatchAnalytics: "Spielanalyse",
  Notifications: "Meldungen",
  AppHealthStatus: "Gesundheitszustand der App",
  ReportBug: "Fehler oder Problem melden",
  SignIn: "Anmelden",
  LoggedIn: "Angemeldet als {username}",
  Videos: "Videos",
  FAQs: "FAQs",
  Subscription: "Abonnement",
  EMail: "Email",
  Items: "Objekte", // "Gegenstände" ist zu lang

  ShowHideOverlay: "Overlay im Spiel ein-/ausblenden:",

  RemoveAds: "Werbung entfernen",

  ToggleOverlay: "Schalte das In-Game-Overlay mit {hotkey} um",

  OneMinuteAgo: "vor 1 Minute",
  MinutesAgo: "vor {minutes} Minuten",
  OneHourAgo: "vor 1 Stunde",
  HoursAgo: "vor {hours} Stunden",
  Yesterday: "vor 1 Tag",
  DaysAgo: "vor {days} Tagen",

  ///
  /*version: "Version",
  channel: "Kanal",
  production: "Produktion",
  beta: "Beta",
  settingOther: "Andere",
  profilePrivacy_public: "Publik",
  profilePrivacy_private: "Privat",
  profilePrivacy_smurf: "Smurf",
  statsTooltip: "In den letzten 30 Tagen gespielte Spiele |<br>Siege - Niederlagen |<br>Gewinnrate",
  subsOnly: "Abonnenten",
  HeroPicksAndItemBuilds: "Heldenauswahl & Items",
  WaterAndPowerRunes: "Water & Power Runes",
  YourNameLeaderboard: "Dein Name (für Bestenliste)",
  Modifier: "Schutz",
  Monitor: "Monitor",
  RESET: "ZURÜCKSETZEN",
  ShowhideOverlay: "Spieloverlay ein-/ausblenden",
  Ultimate: "Ulti",
  TIMING_MODIFIERS: "TIMING-MODIFIKATOREN",
  UltimateLevel: "Ultimatives Level",*/
};
