export default {
  Heroes: "Герои",
  Team: "Команда",
  Timers: "Таймеры",
  Runes: "Руны",
  Audio: "Аудио",
  Disabled: "Отсутствует",
  Speaker: "Ус-во вывода",
  Volume: "Громкость",
  Test: "Тест",
  Language: "Язык",
  Infoboxes: "Инфобоксы",

  None: "Отсутствует",
  Alt: "Alt",
  Ctrl: "Ctrl",
  Shift: "Shift",

  Settings: "Настройки",
  MatchAnalytics: "Аналитика матчей",
  Notifications: "Уведомления",
  AppHealthStatus: "Состояние работы приложения",
  ReportBug: "Сообщить об ошибке или проблеме",
  SignIn: "Войти",
  LoggedIn: "Вы вошли как {username}",
  Videos: "Видео",
  FAQs: "FAQs",
  Subscription: "Подписка",
  EMail: "Эл. почта",
  Items: "Предметы",

  showhideOverlay: "Показать/скрыть внутриигровой оверлей:",
  showhideSecondWindow: "Показать/скрыть второе окно:",

  RemoveAds: "Убрать рекламу",

  ToggleOverlay: "Переключать оверлей - {hotkey}",

  Carry: "Carry",
  Mid: "Mid",
  Offlane: "Offlane",
  Support: "Support",
  SoftSupport: "Soft Support",
  HardSupport: "Hard Support",

  MagicalDamage: "Магический урон",
  PhysicalDamage: "Физическое урон",
  PureDamage: "Чистый урон",
  NeutralDamage: "Нейтральный урон",
  UnknownDamage: "Неизвестный урон",

  OneMinuteAgo: "1 минуту назад",
  MinutesAgo: "{minutes} минут назад",
  OneHourAgo: "1 час назад",
  HoursAgo: "{hours} часов назад",
  Yesterday: "1 день назад",
  DaysAgo: "{days} дней назад",
  /*
  //
  production: "Разработка",
  beta: "Бета",
  settingOther: "Другие",
  profilePrivacy_public: "Открытый",
  profilePrivacy_private: "Закрытый",
  profilePrivacy_smurf: "Cмурф",
  statsTooltip: "Матчи, сыгранные за последние 30 дней |<br>победы - поражения |<br>процент побед",
  subsOnly: "Только подписчики",
  WaterAndPowerRunes: "Руны воды и усилений",
  
  YourNameLeaderboard: "Имя (для рейтинга)",
  Modifier: "Модификатор",
  Monitor: "Монитор",
  RESET: "СБРОС",
  ShowhideOverlay: "Показать/скрыть внутриигровой оверлей",
  Ultimate: "Ультимейт",
  TIMING_MODIFIERS: "МОДИФИКАТОРЫ ТАЙМИНГОВ",
  UltimateLevel: "Уровень Ультимейта",
    HeroPicksAndItemBuilds: "Герои и предметы",

  */
};
