// DO NOT EDIT THIS FILE - IT IS A WASTE OF TIME

export default {
  dotaCoachUsers: {
    en: "Players using Dota Coach",
    de: "Spieler die Dota Coach verwenden",
    fr: "Joueurs utilisant Dota Coach", // #toBeUpdated
    ru: "Игроки, использующие Dota Coach",
    id: "Pemain menggunakan Dota Coach", // #toBeUpdated
    fil: "Ang mga manlalaro gamit ang Dota Coach", // #toBeUpdated
    zh: "此玩家正在使用DotaCoach",
    br: "Jogadores usando Dota Coach",
    es: "Jugadores que usan Dota Coach", // #toBeUpdated
  },

  dotaCoachUsersTeam: {
    en: "In your team: ####",
    de: "In deinem Team: ####",
    fr: "Dans votre équipe : ####", // #toBeUpdated
    ru: "В вашей команде: ####",
    id: "Dalam tim Anda: ####", // #toBeUpdated
    fil: "Sa iyong koponan: ####", // #toBeUpdated
    zh: "在你的团队中：####", // #toBeUpdated
    br: "Em sua equipe: ####",
    es: "En tu equipo: ####", // #toBeUpdated
  },

  dotaCoachUsersEnemy: {
    en: "In enemy team: ####",
    de: "Im gegnerischen Team: ####",
    fr: "Dans l'équipe ennemie : ####", // #toBeUpdated
    ru: "Во вражеской команде: ####",
    id: "Dalam tim musuh: ####", // #toBeUpdated
    fil: "Sa koponan ng kaaway: ####", // #toBeUpdated
    zh: "在敌方队伍中：####", // #toBeUpdated
    br: "Na equipe inimiga: ####",
    es: "En el equipo enemigo: ####", // #toBeUpdated
  },
  spectatingMessage: {
    en: "Enjoy watching!",
    de: "Viel Spaß beim Zusehen!",
    fr: "Profitez de regarder !", // #toBeUpdated
    ru: "Приятного просмотра!",
    id: "Nikmati menonton!", // #toBeUpdated
    fil: "Tangkilikin ang panonood!", // #toBeUpdated
    zh: "享受观看比赛的乐趣吧！",
    br: "Aproveite!",
    es: "¡Disfruta viendo!", // #toBeUpdated
  },

  noRosterMessage: {
    en: "Waiting for information on players...",
    de: "Warte auf Spielerinformationen...",
    fr: "En attente d'informations sur les joueurs...", // #toBeUpdated
    ru: "Ожидание информации об игроках...",
    id: "Menunggu informasi tentang pemain...", // #toBeUpdated
    fil: "Naghihintay para sa impormasyon sa mga manlalaro...", // #toBeUpdated
    zh: "正在等待玩家信息",
    br: "Aguardando informação dos jogadores...",
    es: "Esperando información sobre los jugadores...", // #toBeUpdated
  },

  banSuggestions: {
    en: "Ban suggestions",
    de: "Ban Vorschläge",
    fr: "Suggestions", // #toBeUpdated
    ru: "Предложения по банам",
    id: "Saran larangan", // #toBeUpdated
    fil: "Mga mungkahi Ban", // #toBeUpdated
    zh: "禁用英雄建议",
    br: "Sugestão de ban",
    es: "Sugerencias de prohibición", // #toBeUpdated
  },

  winLoseStreakNone: {
    en: "No win/lose streak in the last three matches.",
    de: "Keine Sieges/Niederlagen Serie in den letzten 3 Spielen.",
    fr: "Aucune série de victoires/défaites lors des trois derniers matchs.", // #toBeUpdated
    ru: "В последних трех матчах отсутствуют серии побед и поражений.",
    id: "Tidak ada kemenangan beruntun dalam tiga pertandingan terakhir.", // #toBeUpdated
    fil: "Walang manalo/mawalan ng streak sa huling tatlong tugma.", // #toBeUpdated
    zh: "没有三连胜或者三连败",
    br: "Nenhuma sequência de vitória/perda nas últimas 3 partidas",
    es: "Sin racha de victorias y derrotas en los últimos tres partidos.", // #toBeUpdated
  },

  matches: {
    en: "Matches",
    de: "Spiele",
    fr: "Matchs", // #toBeUpdated
    ru: "Матчи",
    id: "Pertandingan", // #toBeUpdated
    fil: "Mga Tugma", // #toBeUpdated
    zh: "比赛",
    br: "Partidas",
    es: "Partidos", // #toBeUpdated
  },

  // 'Notifications' exists already in settings
  MatchAnalytics: {
    en: "Match Analytics",
    de: "Spielanalyse",
    fr: "Analyse des matchs",
    ru: "Аналитика матчей",
    id: "Match Analytics", // #toBeUpdated
    fil: "Itugma ang Analytics", // #toBeUpdated
    zh: "匹配分析", // #toBeUpdated
    br: "Análise de partida",
    es: "Análisis de partidos", // #toBeUpdated
  },

  MatchAnayltics: {
    en: "MATCH ANALYTICS",
    de: "SPIELANALYSE",
    fr: "ANALYSE DES MATCHS",
    ru: "АНАЛИТИКА МАТЧЕЙ",
    id: "ANALISIS PERTANDINGAN", // #toBeUpdated
    fil: "TUMUGMA SA ANALYTICS", // #toBeUpdated
    zh: "匹配分析", // #toBeUpdated
    br: "ANÁLISE DE PARTIDA",
    es: "ANÁLISIS DE PARTIDOS", // #toBeUpdated
  },
  percentile: {
    en: "percentile",
    de: "Perzentil",
    fr: "percentile",
    ru: "процентиль",
    id: "persentil", // #toBeUpdated
    fil: "percentile", // #toBeUpdated
    zh: "百分位数", // #toBeUpdated
    br: "percentil",
    es: "percentil", // #toBeUpdated
  },
  Item: {
    en: "Item",
    de: "Gegenstand", // #toBeUpdated
    fr: "Article", // #toBeUpdated
    ru: "Предмет",
    id: "Butir", // #toBeUpdated
    fil: "Item", // #toBeUpdated
    zh: "物品", // #toBeUpdated
    br: "Item",
    es: "Ítem", // #toBeUpdated
  },
  BenchmarkMedian: {
    en: "Benchmark<br>Median",
    de: "Benchmark<br>Mittelwert", // #toBeUpdated
    fr: "Médiane de<br>référence", // #toBeUpdated
    ru: "Медиана контрольного<br>показателя",
    id: "Acuan<br>Median", // #toBeUpdated
    fil: "Benchmark<br>Median", // #toBeUpdated
    zh: "基准中位数", // #toBeUpdated
    br: "Mediana de<br>referência",
    es: "Mediana de<br>referencia", // #toBeUpdated

    /*en: "Median",
      de: "Median", // #toBeUpdated
      fr: "Médiane", // #toBeUpdated
      ru: "Медиана",
      id: "Median", // #toBeUpdated
      fil: "Median", // #toBeUpdated
      zh: "中位数", // #toBeUpdated
      br: "Mediana", // #toBeUpdated
      es: "Mediana", // #toBeUpdated*/
  },
  Best: {
    en: "Best",
    de: "Am besten",
    fr: "Meilleur",
    ru: "Лучшее",
    id: "Terbaik", // #toBeUpdated
    fil: "Pinakamahusay", // #toBeUpdated
    zh: "最好", // #toBeUpdated
    br: "Melhor",
    es: "Mejor", // #toBeUpdated
  },
  Delta: {
    // 'Delta' compared to benchmark / your results
    en: "Delta",
    de: "Abweichung", // #toBeUpdated
    fr: "Différence", // #toBeUpdated
    ru: "Дельта",
    id: "kuala", // #toBeUpdated
    fil: "Delta", // #toBeUpdated
    zh: "三角洲", // #toBeUpdated
    br: "Delta",
    es: "Delta", // #toBeUpdated
  },
  SelectMatch: {
    en: "Select Match",
    de: "Wähle Spiel",
    fr: "Choisir Jeu",
    ru: "Выберите матч",
    id: "Pilih Cocok", // #toBeUpdated
    fil: "Piliin ang Pagtutugma", // #toBeUpdated
    zh: "选择 “匹配”", // #toBeUpdated
    br: "Selecionar partida",
    es: "Seleccionar partido", // #toBeUpdated
  },
  SelectBenchmark: {
    en: "Select Benchmark",
    de: "Wähle Benchmark",
    fr: "Sélectionnez Benchmark",
    ru: "Выберите контрольный показатель",
    id: "Pilih Tolok Ukur", // #toBeUpdated
    fil: "Piliin ang Benchmark", // #toBeUpdated
    zh: "选择基准", // #toBeUpdated
    br: "Selecionar referência",
    es: "Seleccione Benchmark", // #toBeUpdated
  },
  NoBenchmarkData: {
    en: "Attention: Peer benchmark data is currently not available",
    de: "Achtung: Peer-Benchmark-Daten sind derzeit nicht verfügbar", // #toBeUpdated
    fr: "Attention : Les données de référence des pairs ne sont actuellement pas disponibles", // #toBeUpdated
    ru: "Внимание: данные одноранговых тестов в настоящее время недоступны",
    id: "Perhatian: Data patokan peer saat ini tidak tersedia", // #toBeUpdated
    fil: "Pansin: Kasalukuyang hindi magagamit ang data ng benchmark ng Peer", // #toBeUpdated
    zh: "注意：同行基准测试数据目前不可用", // #toBeUpdated
    br: "Atenção: Os dados de referência de outros não estão disponíveis no momento",
    es: "Atención: los datos de referencia de pares no están disponibles actualmente", // #toBeUpdated
  },
  RetryFetchBenchmark: {
    en: "Try to fetch benchmark data again",
    de: "Verusche Benchmark-Daten erneut abzurufen", // #toBeUpdated
    fr: "Essayez à nouveau de charger les données de référence", // #toBeUpdated
    ru: "Попробуйте обновить контрольные данные",
    id: "Cobalah untuk mengambil data patokan lagi", // #toBeUpdated
    fil: "Subukang kunin muli ang data ng benchmark", // #toBeUpdated
    zh: "尝试再次获取基准数据", // #toBeUpdated
    br: "Tente buscar dados de referência novamente",
    es: "Intente recuperar datos de referencia de nuevo", // #toBeUpdated
  },
  Today: {
    en: "Today",
    de: "Heute",
    fr: "Aujourd'hui",
    ru: "Сегодня",
    id: "Hari ini", // #toBeUpdated
    fil: "Ngayon", // #toBeUpdated
    zh: "今天", // #toBeUpdated
    br: "Hoje",
    es: "Hoy", // #toBeUpdated
  },
  DaysAgo: {
    // used to display "5 days ago" ; '$1' sign represents number of days
    en: "{days} days ago",
    de: "Vor {days} Tagen", // #toBeUpdated
    fr: "Il y a {days} jours", // #toBeUpdated
    ru: "{days} дней назад",
    id: "{days} hari lalu", // #toBeUpdated
    fil: "{days} mga araw na nakalipas", // #toBeUpdated
    zh: "{days} 天前", // #toBeUpdated
    br: "há {days} dias",
    es: "Hace {days} días", // #toBeUpdated
  },
  Heroes: {
    en: "Heroes",
    de: "Helden",
    fr: "Héros",
    ru: "Герои", // #toBeUpdated
    id: "Pahlawan", // #toBeUpdated
    fil: "Bayani", // #toBeUpdated
    zh: "英雄", // #toBeUpdated
    br: "Heróis",
    es: "Héroes", // #toBeUpdated
  },
  Steam: {
    en: "Steam",
    de: "Steam", // #toBeUpdated
    fr: "Steam", // #toBeUpdated
    ru: "Steam",
    id: "Steam", // #toBeUpdated
    fil: "Steam", // #toBeUpdated
    zh: "Steam", // #toBeUpdated
    br: "Steam",
    es: "Steam", // #toBeUpdated
  },
  Coaching: {
    en: "Coaching",
    de: "Coaching", // #toBeUpdated
    fr: "Coaching", // #toBeUpdated
    ru: "Тренерство",
    id: "Coaching", // #toBeUpdated
    fil: "Pagtuturo", // #toBeUpdated
    zh: "辅导", // #toBeUpdated
    br: "Coaching",
    es: "Coaching", // #toBeUpdated
  },
  GetPersonalCoach: {
    en: "Get personal coach",
    de: "Hole dir einen persönlichen Coach",
    fr: "Obtenez un coach personnel",
    ru: "Получите персонального тренера",
    id: "Dapatkan pelatih pribadi", // #toBeUpdated
    fil: "Kumuha ng personal na coach", // #toBeUpdated
    zh: "找私人教练", // #toBeUpdated
    br: "Obtenha um treinador pessoal",
    es: "Consigue un entrenador personal", // #toBeUpdated
  },
  ParseMatch: {
    en: "PARSE MATCH",
    de: "PARSE SPIEL", // #toBeUpdated
    fr: "MATCH D'ANALYSE", // #toBeUpdated
    ru: "РАЗБОР МАТЧА",
    id: "MENGURAI PERTANDINGAN", // #toBeUpdated
    fil: "I-PARSE ANG TUGMA", // #toBeUpdated
    zh: "解析匹配", // #toBeUpdated
    br: "ANALISAR PARTIDA",
    es: "ANALIZAR COINCIDENCIA", // #toBeUpdated
  },
  XPM: {
    en: "XPM",
    de: "XPM", // #toBeUpdated
    fr: "XPM", // #toBeUpdated
    ru: "XPM",
    id: "XPM", // #toBeUpdated
    fil: "XPM", // #toBeUpdated
    zh: "XPM", // #toBeUpdated
    br: "XPM",
    es: "XPM", // #toBeUpdated
  },
  FEEDBACK: {
    en: "FEEDBACK",
    de: "FEEDBACK",
    fr: "COMMENTAIRES",
    ru: "ОТЗЫВ",
    id: "UMPAN BALIK",
    fil: "FEEDBACK",
    zh: "反馈",
    br: "COMENTÁRIOS",
    es: "COMENTARIOS",
  },
  ReportAnIssue: {
    en: "Report an issue/bug or request support",
    de: "Ein Problem/Bug melden oder Support anfragen",
    fr: "Signaler un problème/un bogue ou demander de l'aide",
    ru: "Сообщить об ошибке или обратиться в поддержку",
    id: "Melaporkan masalah/bug atau meminta dukungan",
    fil: "Mag-report ng issue/bug o mag-request ng support",
    zh: "报告问题/错误或请求支持",
    br: "Reportar um problema",
    es: "Reportar un problema",
  },
  SEND_REPORT: {
    en: "SEND REPORT",
    de: "BERICHT SENDEN",
    fr: "ENVOYER UN RAPPORT",
    ru: "ОТПРАВИТЬ ОТЧЕТ",
    id: "KIRIM LAPORAN",
    fil: "SEND REPORT",
    zh: "发送报告",
    br: "ENVIAR REPORTE",
    es: "ENVIAR REPORTE",
  },
  ContactDetails: {
    en: "Contact details (E-Mail/Discord)",
    de: "Kontaktdaten (E-Mail/Discord)",
    fr: "Coordonnées (E-Mail/Discord)",
    ru: "Контактные данные (E-Mail/Discord)",
    id: "Rincian kontak (E-Mail/Perselisihan)",
    fil: "Contact details (E-Mail/Discord)",
    zh: "联系方式（电子邮件/Discord）",
    br: "Detalhes de contato (E-Mail/Discord)",
    es: "Detalles de contacto (E-Mail/Discord)",
  },

  EnterContactDetails: {
    en: "Enter your contact details",
    de: "Gib deine Kontaktdaten ein",
    fr: "Entrez vos coordonnées",
    ru: "Введите свои контактные данные",
    id: "Masukkan detail kontak Anda",
    fil: "Ilagay mo ang iyong contact details",
    zh: "输入您的联系方式",
    br: "Insira seus detalhes de contato",
    es: "Ingrese sus datos de contacto",
  },
};
